pipeline:
  clone:
    image: plugins/git
  build:
    image: golang
    commands:
      - go version
      - go env
      - make build
      - make test

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: build